# Generated by Django 5.2.6 on 2025-12-01 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='챔피언 이름')),
            ],
            options={
                'verbose_name': '챔피언',
                'verbose_name_plural': '챔피언 목록',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='리그 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField(verbose_name='경기 날짜')),
                ('stage', models.CharField(choices=[('SW_R1', '스위스 스테이지 R1'), ('SW_R2', '스위스 스테이지 R2'), ('SW_R3', '스위스 스테이지 R3'), ('SW_R4', '스위스 스테이지 R4'), ('SW_R5', '스위스 스테이지 R5'), ('QF', '8강'), ('SF', '4강'), ('F', '결승전')], max_length=10, verbose_name='경기 단계')),
            ],
            options={
                'verbose_name': '경기',
                'verbose_name_plural': '경기 목록',
            },
        ),
        migrations.CreateModel(
            name='PickBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pb_type', models.CharField(choices=[('BAN', 'Ban'), ('PICK', 'Pick')], max_length=4, verbose_name='유형')),
                ('order', models.IntegerField(verbose_name='벤/픽 순서 (1~20)')),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.champion', verbose_name='대상 챔피언')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.match', verbose_name='해당 경기')),
            ],
            options={
                'verbose_name': '벤픽 행동',
                'verbose_name_plural': '벤픽 행동 목록',
                'ordering': ['match', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='선수 이름')),
            ],
        ),
        migrations.CreateModel(
            name='ChampionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_picks', models.IntegerField(default=0, verbose_name='총 픽 횟수')),
                ('blue_first_pick', models.IntegerField(default=0, verbose_name='블루 1픽')),
                ('red_first_pick', models.IntegerField(default=0, verbose_name='레드 1픽')),
                ('tier_score', models.FloatField(default=0.0, verbose_name='Tier Score (가치 점수)')),
                ('side_index', models.FloatField(default=0.0, verbose_name='Side Index (진영 선호도 수치)')),
                ('side_preference', models.CharField(choices=[('BLUE_MUST', '블루 필수'), ('BLUE_PREF', '블루 선호'), ('BLUE_WEAK', '약한 블루'), ('BALANCED', '균형'), ('RED_WEAK', '약한 레드'), ('RED_PREF', '레드 선호'), ('RED_MUST', '레드 필수')], default='BALANCED', max_length=10, verbose_name='진영 선호도')),
                ('champion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='main.champion', verbose_name='챔피언')),
            ],
            options={
                'verbose_name': '챔피언 통계',
                'verbose_name_plural': '챔피언 통계 목록',
                'ordering': ['-tier_score'],
            },
        ),
        migrations.CreateModel(
            name='PBContext',
            fields=[
                ('pick_ban', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.pickban')),
                ('story_label', models.CharField(choices=[('META_BAN', '메타 벤'), ('COUNTER_BAN', '카운터 벤'), ('SNIPER_BAN', '저격 벤'), ('META_PICK', '메타 픽'), ('COUNTER_PICK', '카운터 픽'), ('COMBO_PICK', '조합 픽'), ('WILD_PICK', '사파 픽'), ('ROMANCE_PICK', '낭만 픽'), ('NONE', '분류 없음')], default='NONE', max_length=20, verbose_name='분류 라벨')),
                ('story_keyword', models.CharField(max_length=100, verbose_name='스토리 핵심 키워드')),
                ('expert_comment', models.TextField(blank=True, null=True, verbose_name='전문가/여론 분석 (스토리)')),
                ('emotional_intensity', models.IntegerField(default=0, verbose_name='심리적 강도 (-5 ~ 5)')),
            ],
            options={
                'verbose_name': 'PB 맥락 (스토리텔링)',
                'verbose_name_plural': 'PB 맥락 (스토리텔링) 목록',
            },
        ),
        migrations.AddField(
            model_name='pickban',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.player', verbose_name='선수 (픽인 경우)'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='팀 이름')),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.league', verbose_name='소속 리그')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team', verbose_name='소속 팀'),
        ),
        migrations.AddField(
            model_name='pickban',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.team', verbose_name='수행 팀'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='main.team', verbose_name='Team A'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='main.team', verbose_name='Team B'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='won_matches', to='main.team', verbose_name='승리 팀'),
        ),
        migrations.AlterUniqueTogether(
            name='pickban',
            unique_together={('match', 'order')},
        ),
    ]
