# Generated by Django 5.2.6 on 2025-12-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('QF', '8강'), ('SF', '4강'), ('F', '결승')], max_length=5, verbose_name='경기 단계')),
                ('match_number', models.IntegerField(verbose_name='경기 번호')),
                ('set_number', models.IntegerField(verbose_name='세트 번호')),
                ('team_a', models.CharField(max_length=100, verbose_name='Team A')),
                ('team_b', models.CharField(max_length=100, verbose_name='Team B')),
                ('winner', models.CharField(max_length=100, verbose_name='세트 승리팀')),
                ('final_score', models.CharField(blank=True, max_length=10, verbose_name='최종 스코어')),
                ('match_overview', models.TextField(blank=True, verbose_name='경기 총평')),
                ('banpick_analysis', models.TextField(verbose_name='밴픽 전략 분석')),
                ('game_narrative', models.TextField(verbose_name='경기 흐름 및 핵심 서사')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '경기 스토리',
                'verbose_name_plural': '경기 스토리 목록',
                'ordering': ['stage', 'match_number', 'set_number'],
                'unique_together': {('stage', 'match_number', 'set_number')},
            },
        ),
    ]
