# Generated by Django 5.2.6 on 2025-12-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_matchstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstory',
            name='key_champions',
            field=models.CharField(blank=True, help_text='쉼표로 구분된 챔피언 영문명 (예: Ryze,Neeko,Wukong)', max_length=500, verbose_name='주요 챔피언'),
        ),
    ]
